/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.MascotaControlador;
/**
 *
 * @author USUARIO
 */
public class MascotaGUI extends javax.swing.JFrame {
    private final MascotaControlador control = new MascotaControlador();
    /**
     * Creates new form Mascota
     */ 
    
    public MascotaGUI() {
        ClosePrompt.attachTo(this);
        Vista.SimpleMenuBar.attachTo(this);
        initComponents();
        setTitle("Mascota");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        labelNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        labelRaza = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelIngreso = new javax.swing.JLabel();
        labelOrigen = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        raza = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        origen = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        ingreso = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seleccione una de las opciones");

        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar mascota", "Consultar mascota", "Actualizar mascota", "Listar mascotas", "Eliminar mascota", "Gestionar vacunas" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        labelRaza.setText("Raza");

        labelEdad.setText("Edad");

        labelTipo.setText("Tipo");

        labelId.setText("ID");

        labelPeso.setText("Peso");

        labelIngreso.setText("Fecha de Ingreso");

        labelOrigen.setText("Origen");

        labelGenero.setText("Genero");

        labelPrecio.setText("Precio");

        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        raza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaActionPerformed(evt);
            }
        });

        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenActionPerformed(evt);
            }
        });

        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });

        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Menu mascota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(69, 69, 69)
                                .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre)
                                    .addComponent(labelTipo)
                                    .addComponent(labelEdad)
                                    .addComponent(labelRaza)
                                    .addComponent(labelId)
                                    .addComponent(labelPeso)
                                    .addComponent(labelIngreso)
                                    .addComponent(labelOrigen)
                                    .addComponent(labelGenero)
                                    .addComponent(labelPrecio))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(origen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAceptar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel4)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRaza)
                    .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdad)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIngreso)
                    .addComponent(ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrigen)
                    .addComponent(origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGenero)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Menu accesorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(261, 261, 261)
                    .addComponent(jLabel3)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(jLabel3)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch (opcion.getSelectedItem().toString()) {
            case "Agregar mascota":
            activarTodo();
            break;
            case "Consultar mascota":
            activarSoloDocumento();
            break;
            case "Actualizar mascota":
            activarTodo();
            break;
            case "Listar mascotas":
            activarSoloDocumento();
            labelId.setEnabled(false);
            id.setEnabled(false);
            break;
            case "Eliminar mascota":
            activarSoloDocumento();
            break;
            case "Gestionar vacunas":
                VacunaGUI vacunaGUI = new VacunaGUI();
                vacunaGUI.setVisible(true);
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void razaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch (opcion.getSelectedItem().toString()) {
        case "Agregar mascota": {
            // Verificación previa de todos los campos (texto + numéricos)
            if (!camposObligatoriosLlenos()) return;

            Integer edadVal = parseIntOrWarn(edad, "Edad");
            Double pesoVal = parseDoubleOrWarn(peso, "Peso");
            Double precioVal = parseDoubleOrWarn(precio, "Precio");
            if (edadVal == null || pesoVal == null || precioVal == null) return;

            control.almacenarMascota(
                nombre.getText().trim().toUpperCase(),
                raza.getText().trim().toUpperCase(),
                edadVal,
                tipo.getText().trim().toUpperCase(),
                id.getText().trim(),
                pesoVal,
                ingreso.getText().trim(),
                origen.getText().trim().toUpperCase(),
                genero.getText().trim().toUpperCase(),
                precioVal
            );
            break;
        }
        case "Consultar mascota":
            control.consultarMascota(id.getText().trim());
            break;

        case "Actualizar mascota": {
            if (!camposObligatoriosLlenos()) return;

            Integer edadVal = parseIntOrWarn(edad, "Edad");
            Double pesoVal = parseDoubleOrWarn(peso, "Peso");
            Double precioVal = parseDoubleOrWarn(precio, "Precio");
            if (edadVal == null || pesoVal == null || precioVal == null) return;

            control.actualizarMascota(
                nombre.getText().trim().toUpperCase(),
                raza.getText().trim().toUpperCase(),
                edadVal,
                tipo.getText().trim().toUpperCase(),
                id.getText().trim(),
                pesoVal,
                ingreso.getText().trim(),
                origen.getText().trim().toUpperCase(),
                genero.getText().trim().toUpperCase(),
                precioVal
            );
            break;
        }
        case "Listar mascotas":
            control.listarMascotas();
            break;
        case "Eliminar mascota":
            control.eliminarMascota(id.getText().trim());
            break;
        case "Gestionar vacunas":
            // Ya lo manejas en opcionActionPerformed
            break;
    }
    }//GEN-LAST:event_botonAceptarActionPerformed
public void activarTodo() {
        labelNombre.setEnabled(true);
        nombre.setEnabled(true);
        labelRaza.setEnabled(true);
        raza.setEnabled(true);
        labelEdad.setEnabled(true);
        edad.setEnabled(true);
        labelTipo.setEnabled(true);
        tipo.setEnabled(true);
        labelId.setEnabled(true);
        id.setEnabled(true);
        labelPeso.setEnabled(true);
        peso.setEnabled(true);
        labelIngreso.setEnabled(true);
        ingreso.setEnabled(true);
        labelOrigen.setEnabled(true);
        origen.setEnabled(true);
        labelGenero.setEnabled(true);
        genero.setEnabled(true);
        labelPrecio.setEnabled(true);
        precio.setEnabled(true);
    }

    public void activarSoloDocumento() {
        labelNombre.setEnabled(false);
        nombre.setEnabled(false);
        labelRaza.setEnabled(false);
        raza.setEnabled(false);
        labelEdad.setEnabled(false);
        edad.setEnabled(false);
        labelTipo.setEnabled(false);
        tipo.setEnabled(false);
        labelId.setEnabled(true);
        id.setEnabled(true);
        labelPeso.setEnabled(false);
        peso.setEnabled(false);
        labelIngreso.setEnabled(false);
        ingreso.setEnabled(false);
        labelOrigen.setEnabled(false);
        origen.setEnabled(false);
        labelGenero.setEnabled(false);
        genero.setEnabled(false);
        labelPrecio.setEnabled(false);
        precio.setEnabled(false);
    }
    private Integer parseIntOrWarn(javax.swing.JTextField field, String label) {
    String v = field.getText() == null ? "" : field.getText().trim();
    if (v.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                label + " no puede estar vacío.",
                "Datos incorrectos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        field.requestFocus();
        return null;
    }
    try {
        return Integer.parseInt(v);
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                label + " debe ser un número entero.",
                "Datos incorrectos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        field.requestFocus();
        return null;
    }
}

private Double parseDoubleOrWarn(javax.swing.JTextField field, String label) {
    String v = field.getText() == null ? "" : field.getText().trim();
    if (v.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                label + " no puede estar vacío.",
                "Datos incorrectos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        field.requestFocus();
        return null;
    }
    try {
        return Double.parseDouble(v);
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                label + " debe ser un número.",
                "Datos incorrectos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        field.requestFocus();
        return null;
    }
}
private boolean camposObligatoriosLlenos() {
    // Campos obligatorios en agregar / actualizar
    String n = nombre.getText().trim();
    String r = raza.getText().trim();
    String e = edad.getText().trim();
    String t = tipo.getText().trim();
    String i = id.getText().trim();
    String p = peso.getText().trim();
    String f = ingreso.getText().trim();
    String o = origen.getText().trim();
    String g = genero.getText().trim();
    String pr = precio.getText().trim();

    // Opción simple: si cualquiera está vacío -> mensaje general
    if (n.isEmpty() || r.isEmpty() || e.isEmpty() || t.isEmpty() || i.isEmpty()
            || p.isEmpty() || f.isEmpty() || o.isEmpty() || g.isEmpty() || pr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe llenar todos los datos.",
                "Datos incompletos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MascotaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField id;
    private javax.swing.JTextField ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelIngreso;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelOrigen;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelRaza;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JTextField origen;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField raza;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
