/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.ConsultaDTO;
import Implement.ConsultaDAOFile;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author USUARIO
 */
public class TablaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public TablaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Mascota", "Nombre Mascota", "Fecha", "Síntomas", "Tratamiento"
            }
        ){
            boolean[] canEdit = new boolean []{
                false, false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaConsulta().setVisible(true);
            }
        });
    }
    public void llenarTablaPorMascota(List<ConsultaDTO> consultas) {
    // Suponiendo que usas JTable llamado tablaConsultas y DefaultTableModel
    DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
    modelo.setRowCount(0); // Limpia la tabla

    for (ConsultaDTO consulta : consultas) {
        Object[] fila = {
            consulta.getIdMascota(),
            consulta.getNombreMascota(),
            // Formatea la fecha como desees
            new SimpleDateFormat("yyyy-MM-dd").format(consulta.getFecha()),
            consulta.getSintomas(),
            consulta.getTratamiento()
        };
        modelo.addRow(fila);
    }
    // Puedes refrescar la tabla si es necesario
}
   public void llenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) this.tabla1.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de agregar datos
        List<ConsultaDTO> consultas = new ConsultaDAOFile().listarConsultas();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        for(ConsultaDTO consulta : consultas){
            String[] fila = {
                consulta.getIdMascota(),
                consulta.getNombreMascota(),
                sdf.format(consulta.getFecha()),
                consulta.getSintomas(),
                consulta.getTratamiento()
            };
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
