/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.VentaDTO;
import Modelo.DetalleDTO;
import Implement.VentaDAOFile;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USUARIO
 */
public class TablaVenta extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public TablaVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venta", "Id Cliente", "Id Vendedor", "Id Mascota", "Fecha", "Total", "Accesorios"
            }
        ){
            boolean[] canEdit = new boolean []{
                false, false, false, false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaVenta().setVisible(true);
            }
        });
    }
  public void llenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) this.tablaVenta.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de llenarla
        List<VentaDTO> ventas = new VentaDAOFile().listarVentas();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");

        for (VentaDTO venta : ventas) {
            String accesorios = "";
            List<DetalleDTO> detalles = venta.getDetallesAccesorio();
            if (detalles != null && !detalles.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (DetalleDTO det : detalles) {
                    sb.append("[").append(det.getIdAccesorio())
                      .append(", Cant: ").append(det.getCantidad())
                      .append(", $").append(det.getPrecioUnitario()).append("] ");
                }
                accesorios = sb.toString();
            } else {
                accesorios = "Sin accesorios";
            }
            String[] fila = {
                venta.getIdVenta(),
                venta.getIdCliente(),
                venta.getIdVendedor(),
                (venta.getIdMascota() != null && !venta.getIdMascota().isEmpty()) ? venta.getIdMascota() : "Sin mascota",
                (venta.getFecha() != null ? sdf.format(venta.getFecha()) : ""),
                String.valueOf(venta.getTotal()),
                accesorios
            };
            modelo.addRow(fila);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVenta;
    // End of variables declaration//GEN-END:variables
}
