package Vista;

import Modelo.MascotaDTO;
import Modelo.VacunaDTO;
import Modelo.DosisDTO;
import Implement.MascotaDAOFile;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class TablaMascota extends javax.swing.JFrame {

    static class MultiLineTableCellRenderer extends JTextArea implements TableCellRenderer {

        public MultiLineTableCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value != null ? value.toString() : "");
            setSize(table.getColumnModel().getColumn(column).getWidth(), getPreferredSize().height);
            if (isSelected) {
                setBackground(table.getSelectionBackground());
                setForeground(table.getSelectionForeground());
            } else {
                setBackground(table.getBackground());
                setForeground(table.getForeground());
            }
            return this;
        }
    }

    /**
     * Creates new form TablaEstudiantes
     */
    public TablaMascota() {
        initComponents();
        ajustarColumnas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setFont(new java.awt.Font("Candara", 0, 14));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Raza", "Edad", "Tipo", "Id", "Peso", "Ingreso", "Origen", "Genero", "Precio", "Vacuna y Dosis", "Dueño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setToolTipText("");
        tabla.setColumnSelectionAllowed(true);
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tabla);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void ajustarColumnas() {
        int[] anchos = {80, 80, 50, 70, 60, 60, 75, 75, 60, 75, 300, 80};
        TableColumnModel columnModel = tabla.getColumnModel();
        for (int i = 0; i < anchos.length; i++) {
            columnModel.getColumn(i).setPreferredWidth(anchos[i]);
        }
        columnModel.getColumn(10).setCellRenderer(new MultiLineTableCellRenderer());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaMascota().setVisible(true);
            }
        });
    }

    public void llenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) this.tabla.getModel();
        List<MascotaDTO> mascotas = new MascotaDAOFile().listarMascota();
        modelo.setRowCount(0); // Limpiar la tabla antes
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        for (MascotaDTO mascota : mascotas) {
            String vacunasStr = "";
            List<VacunaDTO> vacunas = mascota.getVacunas();
            if (vacunas != null && !vacunas.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (VacunaDTO v : vacunas) {
                    sb.append(v.getTipo()).append(":\n");
                    List<DosisDTO> dosisList = v.getDosis();
                    if (dosisList != null && !dosisList.isEmpty()) {
                        for (int i = 0; i < dosisList.size(); i++) {
                            DosisDTO d = dosisList.get(i);
                            sb.append("  • ").append(sdf.format(d.getFecha())).append(" - Cantidad: ").append(d.getCantidad()).append("\n");
                        }
                    } else {
                        sb.append("  (Sin dosis registradas)\n");
                    }
                    sb.append("\n");
                }
                vacunasStr = sb.toString();
            } else {
                vacunasStr = "Sin vacunas";
            }
            // NUEVO: columna dueño
            String duenio = (mascota.getIdDueño() == null || mascota.getIdDueño().isEmpty())
                    ? "Sin dueño"
                    : mascota.getIdDueño();

            String[] fila = {
                mascota.getNombre(),
                mascota.getRaza(),
                String.valueOf(mascota.getEdad()),
                mascota.getTipo(),
                mascota.getId(),
                String.valueOf(mascota.getPeso()),
                (mascota.getFechaIngreso() != null ? sdf.format(mascota.getFechaIngreso()) : ""),
                mascota.getLugarOrigen(),
                String.valueOf(mascota.getGenero()),
                String.valueOf(mascota.getPrecio()),
                vacunasStr,
                duenio
            };
            modelo.addRow(fila);
        }
        ajustarAltosDeFila();
    }

    // Ajusta la altura de filas para mostrar bien el texto multilínea en la columna de vacunas
    private void ajustarAltosDeFila() {
        int columnaVacunas = 10; // columna de vacuna/dosis
        int columnaDueno = 11;
        int alturaPorDefecto = 20;
        int alturaMaxima = 80;
        TableColumn column = tabla.getColumnModel().getColumn(columnaVacunas);
        for (int row = 0; row < tabla.getRowCount(); row++) {
            Object value = tabla.getValueAt(row, columnaVacunas);
            if (value != null && value.toString().equalsIgnoreCase("Sin vacunas")) {
                tabla.setRowHeight(row, alturaPorDefecto);
                continue;
            }
            TableCellRenderer renderer = column.getCellRenderer();
            Component comp = renderer.getTableCellRendererComponent(tabla, value, false, false, row, columnaVacunas);
            int preferredHeight = comp.getPreferredSize().height;
            int setHeight = Math.max(alturaPorDefecto, Math.min(preferredHeight, alturaMaxima));
            tabla.setRowHeight(row, setHeight);
        }
        // Asegura que la columna dueño esté correctamente visible
        tabla.getColumnModel().getColumn(columnaDueno).setPreferredWidth(80);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
