/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.VentaControlador;
import Modelo.DetalleDTO;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author USUARIO
 */
public class VentaGUI extends javax.swing.JFrame {

    private final VentaControlador ventaControlador = new VentaControlador();

    /**
     * Creates new form Mascota
     */
    public VentaGUI() {
        setTitle("Venta");
        ClosePrompt.attachTo(this);
        initComponents();
        activarRegistroVenta();
        Vista.SimpleMenuBar.attachTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        labelIdVenta = new javax.swing.JLabel();
        idVenta = new javax.swing.JTextField();
        labelIdCliente = new javax.swing.JLabel();
        labelIdVendedor = new javax.swing.JLabel();
        labelIdMascota = new javax.swing.JLabel();
        labelAccesorios = new javax.swing.JLabel();
        idMascota = new javax.swing.JTextField();
        idCliente = new javax.swing.JTextField();
        idVendedor = new javax.swing.JTextField();
        accesorios = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Menu Veterinaria");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        accesorios.setToolTipText("(formato: accesorios:cantidad;id2:cant2;...)");

        jLabel1.setText("Seleccione una de las opciones");

        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar venta", "Listar ventas", "Consultar venta", "Eliminar venta", "Actualizar venta" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });

        labelIdVenta.setText("ID venta");

        idVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVentaActionPerformed(evt);
            }
        });

        labelIdCliente.setText("ID cliente");

        labelIdVendedor.setText("ID vendedor");

        labelIdMascota.setText("ID mascota");

        labelAccesorios.setText("Accesorios");

        idMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMascotaActionPerformed(evt);
            }
        });

        idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteActionPerformed(evt);
            }
        });

        idVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVendedorActionPerformed(evt);
            }
        });

        accesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriosActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Menu venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdVenta)
                            .addComponent(labelIdMascota)
                            .addComponent(labelIdVendedor)
                            .addComponent(labelIdCliente)
                            .addComponent(labelAccesorios))
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAceptar)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(167, 167, 167))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdVenta)
                    .addComponent(idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdCliente)
                    .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdVendedor)
                    .addComponent(idVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdMascota)
                    .addComponent(idMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAccesorios)
                    .addComponent(accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAceptar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        String seleccion = (String) opcion.getSelectedItem();
        switch (seleccion) {
            case "Registrar venta":
                activarRegistroVenta();
                break;
            case "Actualizar venta":
                activarRegistroVenta();
                break;
            case "Listar ventas":
                desactivarRegistroVenta();
                idVenta.setEnabled(false);
                break;
            case "Consultar venta":
                activarSoloIdVenta();
                break;
            case "Eliminar venta":
                activarSoloIdVenta();
                break;
        }

    }//GEN-LAST:event_opcionActionPerformed

    private void idVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVentaActionPerformed

    private void idMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMascotaActionPerformed

    private void idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteActionPerformed

    private void idVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVendedorActionPerformed

    private void accesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoriosActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String seleccion = (String) opcion.getSelectedItem();
        switch (seleccion) {
            case "Registrar venta":
            case "Actualizar venta":
                List<DetalleDTO> detalles = new ArrayList<>();
                String accText = accesorios.getText().trim();
                if (!accText.isEmpty()) {
                    try {
                        String[] items = accText.split(";");
                        Set<String> idsUsados = new HashSet<>();
                        int index = 0;
                        for (String item : items) {
                            index++;
                            item = item.trim();
                            if (item.isEmpty()) {
                                continue;
                            }

                            String[] datos = item.split(":");
                            if (datos.length != 2) {
                                throw new IllegalArgumentException("Error en el accesorio #" + index + ": el formato debe ser id:cantidad.");
                            }

                            String id = datos[0].trim();
                            String cantidadStr = datos[1].trim();

                            if (!id.matches("\\d+")) {
                                throw new IllegalArgumentException("Error en el accesorio #" + index + ": el ID debe ser numérico.");
                            }

                            int cantidad;
                            try {
                                cantidad = Integer.parseInt(cantidadStr);
                            } catch (NumberFormatException e) {
                                throw new IllegalArgumentException("Error en el accesorio #" + index + ": la cantidad debe ser un número entero.");
                            }
                            if (cantidad <= 0) {
                                throw new IllegalArgumentException("Error en el accesorio #" + index + ": la cantidad debe ser mayor a 0.");
                            }

                            if (idsUsados.contains(id)) {
                                throw new IllegalArgumentException("No se puede repetir el ID de accesorio: " + id);
                            }
                            idsUsados.add(id);
                            detalles.add(new DetalleDTO(id, cantidad, 0)); // precio se busca internamente
                        }
                    } catch (IllegalArgumentException e) {
                        JOptionPane.showMessageDialog(
                                this,
                                e.getMessage()
                                + "\n\nFormato esperado: id:cantidad; id:cantidad"
                                + "\nEjemplo: 101:2; 205:1; 333:4",
                                "Formato de accesorios incorrecto",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Formato de accesorios incorrecto.\n\nFormato esperado: id:cantidad; id:cantidad"
                                + "\nEjemplo: 101:2; 205:1; 333:4",
                                "Formato de accesorios incorrecto",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }
                }
                if (seleccion.equals("Registrar venta")) {
                    ventaControlador.registrarVenta(
                            idVenta.getText().trim(),
                            idCliente.getText().trim(),
                            idVendedor.getText().trim(),
                            idMascota.getText().trim(),
                            detalles
                    );
                } else { // Actualizar
                    ventaControlador.actualizarVenta(
                            idVenta.getText().trim(),
                            idCliente.getText().trim(),
                            idVendedor.getText().trim(),
                            idMascota.getText().trim(),
                            detalles
                    );
                }
                break;
            case "Listar ventas":
                TablaVenta tv = new TablaVenta();
                tv.llenarTabla();
                tv.setVisible(true);
                break;
            case "Consultar venta":
                ventaControlador.consultarVenta(idVenta.getText().trim());
                break;
            case "Eliminar venta":
                ventaControlador.eliminarVenta(idVenta.getText().trim());
                break;
        }

    }//GEN-LAST:event_botonAceptarActionPerformed
    private void activarRegistroVenta() {
        labelIdVenta.setEnabled(true);
        idVenta.setEnabled(true);
        labelIdCliente.setEnabled(true);
        idCliente.setEnabled(true);
        labelIdVendedor.setEnabled(true);
        idVendedor.setEnabled(true);
        labelIdMascota.setEnabled(true);
        idMascota.setEnabled(true);
        labelAccesorios.setEnabled(true);
        accesorios.setEnabled(true);
    }

    private void desactivarRegistroVenta() {
        labelIdVenta.setEnabled(true);
        idVenta.setEnabled(true);
        labelIdCliente.setEnabled(false);
        idCliente.setEnabled(false);
        labelIdVendedor.setEnabled(false);
        idVendedor.setEnabled(false);
        labelIdMascota.setEnabled(false);
        idMascota.setEnabled(false);
        labelAccesorios.setEnabled(false);
        accesorios.setEnabled(false);
    }

    private void activarSoloIdVenta() {
        labelIdVenta.setEnabled(true);
        idVenta.setEnabled(true);
        labelIdCliente.setEnabled(false);
        idCliente.setEnabled(false);
        labelIdVendedor.setEnabled(false);
        idVendedor.setEnabled(false);
        labelIdMascota.setEnabled(false);
        idMascota.setEnabled(false);
        labelAccesorios.setEnabled(false);
        accesorios.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accesorios;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField idCliente;
    private javax.swing.JTextField idMascota;
    private javax.swing.JTextField idVendedor;
    private javax.swing.JTextField idVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAccesorios;
    private javax.swing.JLabel labelIdCliente;
    private javax.swing.JLabel labelIdMascota;
    private javax.swing.JLabel labelIdVendedor;
    private javax.swing.JLabel labelIdVenta;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
